### ISSUE TITLE
PyTorch does not currently provide packages for PyPI (see status at https://github.com/pytorch/pytorch/issues/566).

### ISSUE THREAD

**Issue by zhangajie** [zsrkmyn/pytorch_loadcaffe#1]
Hi,I'm newer to pytorch,when I try to "sudo python setup.py install  ",it turns out to be that:

RuntimeError: PyTorch does not currently provide packages for PyPI (see status at https://github.com/pytorch/pytorch/issues/566).
Please follow the instructions at http://pytorch.org/ to install with miniconda instead.
And I dont know how to solve it ,do you have other ways to set it up? Thank you !

**Comment by zsrkmyn** [comment]
http://pytorch.org 上有安装说明。

**Comment by zhangajie** [comment]
这个不是pytorch的安装说明吗，我已经安装了pytorch，然后执行sudo python setup.py install时出了上述错误

**Comment by zsrkmyn** [comment]
哦，还以为你在安装 PyTorch \_(:з」∠)\_

说明 pip 不能找到你安装的 PyTorch

**Comment by zhangajie** [comment]
恩呢，现在安装成功了，但是import loadcaffe时，出现以下错误

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/loadcaffe/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/loadcaffe/__internal/pytorch_loadcaffe.py", line 26, in <module>
  File "build/bdist.linux-x86_64/egg/loadcaffe/__internal/layers.py", line 24, in <module>
ImportError: cannot import name caffe_pb2
请问是需要安装caffe吗？

**Comment by zsrkmyn** [comment]
不需要装 caffe，你有没有有装 protobuf？不是 python-protobuf，就是 protobuf，构建时候需要的。

另外这个项目不是太完整，很多 layer 都不支持，如果你需要可以自己添加一下。

**Comment by zhangajie** [comment]
嗯嗯，谢谢你的帮忙！！！

**Comment by acgtyrant** [comment]
原来你还捣鼓了这项目啊（围观！

不过 PyTorch 0.3 现在支持 ONNX，这项目没必要了吧。

**Comment by zhangajie** [comment]
是吗，我也是才开始学习不久，也不太懂，看来可以好好找一下ONNX相关了

**Comment by zsrkmyn** [comment]
@acgtyrant, 当时因为有个模型需要转换，就随手撸了一个，之后就没管了（所以连 BN 都不支持 😂
